Frontend:
- changed-files:
  - any-glob-to-any-file:
    - pages/**/*
    - components/**/*
    - hooks/**/*
    - styles/**/*
    - public/**/*
    - middleware/**/*

Config:
- changed-files:
  - any-glob-to-any-file:
    - next.config.js
    - tsconfig.json
    - "*.config.js"
    - package.json
    - pnpm-lock.yaml
    - .env*
    - .eslintrc.js
    - .prettierrc
    - .editorconfig

Tests:
- changed-files:
  - any-glob-to-any-file:
    - __tests__/**/*
    - jest.config.js
    - .github/workflows/**/*
    - cypress/**/*
    - testing/**/*

Docs:
- changed-files:
  - any-glob-to-any-file:
    - README.md
    - docs/**/*
    - content/en/**/*

Images:
- changed-files:
  - any-glob-to-any-file:
    - public/images/**/*
    - static/images/**/*

DevEnv:
- changed-files:
  - any-glob-to-any-file:
    - .vscode/**/*
    - .github/**/*

DevOps:
- changed-files:
  - any-glob-to-any-file:
    - Dockerfile
    - docker-compose.yml

release:
 - base-branch: 'main'