name: Clean Branches

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  remove-stale-branches:
    name: Remove Stale Branches
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v2.4.0
        with:
          dry-run: false
          github-token: ${{ secrets.DELETE_STALE_BRANCH_TOKEN }}
          exempt-branches-regex: ^(main|prod)$
          exempt-protected-branches: true
          days-before-branch-stale: 30
          days-before-branch-delete: 90

